spring:
  application:
    name: prod-hive-auth-service

  datasource:

    url: jdbc:postgresql://ep-nameless-base-aicp428n-pooler.c-4.us-east-1.aws.neon.tech:5432/neondb?sslmode=require
    driver-class-name: org.postgresql.Driver
    username: neondb_owner
    password: npg_9wO7vgntzMuc
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  jwt:
    secret: "CHANGE_ME_LATER_CHANGE_ME_LATER_32_CHARACTERS"

server:
  port: 8081
